# =============================================================================
# PROJECT:      SteamMachine-DIY - Complete Dynamic Configuration
# VERSION:      2.1.3 - YAML Architecture
# DESCRIPTION:  Full Gamescope parameters mapping (Converted from Manifesto).
# PHILOSOPHY:   KISS (Keep It Simple, Stupid) - Hardcore Libre Mode
# REPOSITORY:   https://github.com/dlucca1986/SteamMachine-DIY
# PATH:         $HOME/.config/steamos_diy/config.yaml
# LICENSE:      MIT
# =============================================================================

env_vars:
  GAME_WRAPPER: ""
  GAME_EXTRA_ARGS: ""
flags:
  - "--hide-cursor-delay 3000"
post_start_cmds:
